import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Quote } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SectionHeading } from "@/components/site-ui";
import samHenryImage from "@/assets/Sam Henry.jpg";
import asikpoEmmanuellaImage from "@/assets/Asikpo Emmanuella-Joseph.jpg";
import preciousIyanuoluwaImage from "@/assets/Precious Iyanuoluwa.jpg";
import titiloyeDanielImage from "@/assets/Titiloye Daniel Oluwadarasimi.jpg";
import collinsOluchiImage from "@/assets/Collins Oluchi.png";
import udofaMichaelImage from "@/assets/Udofa Michael.png";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "The SMer Space | Hire & Train Social Media Managers" },
    { name: "description", content: "The SMer Space matches brands with certified social media managers and trains aspiring SMMs through a practical masterclass." },
    { property: "og:title", content: "The SMer Space | Hire & Train Social Media Managers" },
    { property: "og:description", content: "Hire the right social media manager or build your own SMM career with The SMer Space." },
    { property: "og:type", content: "website" }, { property: "og:url", content: "/" },
    { name: "twitter:card", content: "summary_large_image" },
  ], links: [{ rel: "canonical", href: "/" }] }),
  component: HomePage,
});

const stats = [["4yr+", "Experience"], ["50+", "Brands"], ["40%+", "Growth"], ["188K", "Views"]];
const team = [
  { name: "Sam Henry", role: "Designer", initials: "SH", image: samHenryImage, bio: "Graphic designer focused on clear communication and visual solutions across social media and brand design.", describe: "My name is Sam Henry. I am a professional graphic designer, who focuses on clear communication and visual solutions, via social media design and brand designs. I am a little bit introverted, and I kinda enjoy my own space. I enjoy making friends with like-minded people, even though I don't have a lot of friends, or any at all. I am what you would consider a person with a slightly monotonous lifestyle, and to be honest, I'm used to it.", fun: "Aside design, I enjoy listening to music as well as singing. I also enjoy doing research (a bit nerdy, actually). I also have a little bit of passion for teaching as well as learning. My lifestyle is a little bizarre, and I doubt if anyone can live this kinda lifestyle." },
  { name: "Asikpo Emmanuella-Joseph", role: "Content Creator", initials: "AE", image: asikpoEmmanuellaImage, bio: "Law graduate and digital creator with a musical heart, a love of good music, and an eye for style.", describe: "My name is Asikpo Emmanuella-Joseph, a lot of people call me Ella, because my name is really long. I also go by the name Joseph, and that also confuses people because Joseph is naturally ascribed to be a man's name. I'm a law graduate and a digital creator. I am also very musically inclined and as such, I enjoy listening to good and clean music, singing and dancing too. I love staying indoors a lot too.", fun: "I love singing and dancing, I do that during my leisure time. I also love styling pieces, and combining outfits. Also, for fun sometimes I like to go window shopping too, just going to a store to check out nice stuff with no intention of buying." },
  { name: "Precious Iyanuoluwa", role: "Content Strategist", initials: "PI", image: preciousIyanuoluwaImage, bio: "Writer, video editor, and fashion designer who brings ideas to life in every creative form she can think of.", describe: "I am Precious Iyanuoluwa; a valuable miracle, because that's exactly what I am. I'm a multi-talented creative, a full-blown introvert, and someone who genuinely loves putting both my hands and my mind to work. Give me movies, popcorn, a comfortable space, and I could probably go years without seeing or talking to people, but don't get me wrong, I do love people. I'm passionate about discipline, growth, and excellence, and I'm always looking for ways to learn, create, improve, and become better. I'm a writer, video editor, and fashion designer, and I love bringing ideas to life in different forms, if you can think of anything creative, there's a good chance I can figure out how to do it.", fun: "I read, write, sing, edit, sew, and occasionally disappear into my own little world. If I'm not creating something, I'm probably thinking about creating something. Basically, I'm happiest when my mind is busy, my hands are creating, and I have enough space to be myself." },
  { name: "Titiloye Daniel Oluwadarasimi", role: "Founder, The SMer Space", initials: "TD", image: titiloyeDanielImage, bio: "Founder and Creative Director of The SMer Space. Drummer, pianist, strategist, and a teacher at heart.", describe: "Most people call me DOT, honestly, a lot of them don't even know my actual name is Daniel. I'm a full-blown introvert who genuinely loves being indoors, I can stay in my room for 7 days straight and not get bored once, ask anyone who knows me. I play the drums and the piano, and my brain simply refuses to function if my space is scattered, so step one of any productive day is always tidying my room first. I don't make friends easily, I'll admit that, but if you're one of the few I've let in, I love you with everything I've got. I love people, genuinely, and it honestly bothers me to see anyone suffer or stay stuck without growing.", fun: "Honestly, I'm that person who will randomly start teaching Maths, Physics, Chemistry, or even medical topics, purely for fun, not because anyone asked. If you ever catch me mid-explanation about something totally unrelated to social media, don't be alarmed, that's just me enjoying myself. I also love planning random games and activities out of nowhere, so if a spontaneous quiz night or a silly challenge ever pops up around me, you'll know exactly who's behind it." },
  { name: "Collins Oluchi", role: "Social Media Manager", initials: "CO", image: collinsOluchiImage, bio: "Quietly observant social media manager who cares deeply about the brands and people she works with.", describe: "Most people know me as Oluchi, although I also go by Lulu sometimes. I'm naturally quiet and very much an introvert, so if I have the choice between going out and staying at home, I'm probably choosing my bed without thinking twice. I'm curious, emotional, and always hungry to learn, and once I set my mind to understand something, I can be surprisingly persistent about it. I love music, especially singing, and I'm the kind of person who can be deeply affected by the little things. I may not always be the loudest person in the room, but I'm observant, I care deeply about the people around me, and I'm always looking for ways to grow and become better at what I do.", fun: "Outside of social media management, I love singing and listening to music. Music has always been one of my favourite ways to relax and express myself, and I can easily lose track of time when I'm listening to a song I really love. I also genuinely enjoy learning new things and exploring creative ideas, so you'll often find me going down random rabbit holes just because something caught my interest. And when I'm not doing any of that, there's a very good chance I'm sleeping." },
  { name: "Udofa Michael", role: "Designer", initials: "UM", image: udofaMichaelImage, bio: "Creative designer who loves turning ideas into experiences, from detailed brand design to AI-powered video.", describe: "Almost all my friends and clients know me as a creative designer, but honestly, I see myself as someone who just loves creating and bringing ideas to life. I'm very particular about details, especially when it comes to design. I love learning, experimenting with new tools, and turning ideas into things people can actually see and experience. I'm also someone who genuinely enjoys helping people grow, whether that's through design, teaching, or simply sharing what I've learned. I'm naturally curious, creative, and always looking for the next thing I can build, learn, or improve.", fun: "Aside from creative designing, I really enjoy creating AI-powered video content, especially content designed to do more than just look good. I love combining AI, storytelling, marketing, and cinematic visuals to create content that can actually generate leads and convert. So if you ever see me testing some random AI idea or trying to make a scene look more realistic, just know I'm probably having fun. I also enjoy teaching and breaking down things I've learned, especially when I can help someone understand something they thought was difficult." },
];
const steps = [["01", "Tell Us Your Brief", "Share your goals, challenges, audience, and budget."], ["02", "Get Matched", "We identify the right certified professional or team."], ["03", "Onboard", "Align on scope, voice, workflow, and priorities."], ["04", "Grow", "Move forward with focused, consistent social media support."]];
const faqs = [
  ["How does matching work?", "Tell us what your brand needs and we’ll recommend a social media manager or agency package that fits your goals and budget."],
  ["Can complete beginners join the masterclass?", "Yes. The 14-module programme is designed to move beginners from the fundamentals toward client-ready skills."],
  ["Do you work with brands outside Nigeria?", "Yes. The team has worked with brands across Nigeria, the UK, and beyond."],
  ["Are package payments made on this website?", "No. Package enquiries and masterclass purchases currently continue through WhatsApp."],
];

function HomePage() {
  return <>
    <section className="home-hero"><div className="site-container"><p className="eyebrow">Social media, handled properly</p><h1>Stop Guessing.<br /><span>Start Hiring Right.</span></h1><p className="hero-copy">The SMer Space connects brands with dedicated social media managers and deploys full agency teams for brands that are ready to grow.</p><div className="flex flex-wrap gap-3"><Button asChild size="xl"><Link to="/hire">Find your SMM <ArrowRight /></Link></Button><Button asChild size="xl" variant="outline"><a href="https://selar.com/m/smer-space1" target="_blank" rel="noreferrer">Buy the course <ArrowRight /></a></Button></div><div className="stats-row">{stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div></section>
    <section className="section"><div className="site-container"><SectionHeading eyebrow="Meet the team" title="The People Behind The Progress." description="The strategists, creators, and designers doing the work at The SMer Space." /><div className="grid gap-6 md:grid-cols-3">{team.map((person) => <article key={person.name} className="team-card"><div className={`team-portrait ${person.name === "Udofa Michael" ? "team-portrait-udofa" : ""}`}>{person.image ? <img src={person.image} alt={person.name} /> : <span>{person.initials}</span>}</div><div><p className="eyebrow">{person.role}</p><h3>{person.name}</h3><p className="team-bio">{person.bio}</p><details className="team-more"><summary>More about {person.name.split(" ")[0]}<span aria-hidden="true">+</span></summary><p>{person.describe}</p><p><strong>A skill I like most</strong>{person.fun}</p></details></div></article>)}</div></div></section>
    <section className="section bg-surface"><div className="site-container grid gap-14 lg:grid-cols-[1.1fr_0.9fr]"><div><SectionHeading eyebrow="Who we are" title="The Industry Needed One Space That Does It All. We Built It." /><div className="space-y-5 text-lg text-muted-foreground"><p>The SMer Space was built for two kinds of people. The business owner who is tired of guessing what to post and needs a professional to handle it. And the aspiring social media manager who is ready to build a real career but does not know where to start.</p><p>We built a platform that solves both problems at once. Businesses come to us and get matched with a certified, professional social media manager at a price point that works for their budget. Aspiring SMMs come to us and get the training, the certification, and the tools they need to land their first client and build a sustainable career.</p><p>This is not just an agency. This is the infrastructure the social media industry has been missing. And we built it from the ground up.</p></div></div><div className="grid gap-px bg-border"><article className="belief-card"><span>Mission</span><p>To train the next generation of social media managers and connect businesses with the right professional for their brand at every budget. We exist to make social media management accessible, professional, and results-driven for everyone.</p></article><article className="belief-card"><span>Vision</span><p>To become the number one social media management platform globally. The name every business calls when they need to grow online and every aspiring SMM turns to when ready to build a career.</p></article></div></div></section>
    <section className="section"><div className="site-container"><SectionHeading eyebrow="How we work" title="Simple. Seamless. Effective." /><div className="grid gap-px border border-border bg-border md:grid-cols-2 lg:grid-cols-4">{steps.map(([number, title, body]) => <article key={number} className="step-card"><strong>{number}</strong><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="section bg-surface"><div className="site-container"><SectionHeading eyebrow="Client stories" title="Proof, Coming Soon." /><div className="empty-testimonial"><Quote /><h3>Real reviews will live here.</h3><p>Testimonials are waiting on your future data connection. This state is intentionally ready for them.</p></div></div></section>
    <section className="section"><div className="site-container"><SectionHeading eyebrow="FAQ" title="A Few Things You May Want To Know." /><div className="divide-y divide-border border-y border-border">{faqs.map(([question, answer]) => <details key={question} className="faq-row"><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="section bg-primary text-primary-foreground"><div className="site-container flex flex-col items-start justify-between gap-8 md:flex-row md:items-center"><h2 className="section-title max-w-2xl">Ready To Stop Guessing?</h2><div className="flex flex-wrap gap-3"><Button asChild variant="inverse" size="lg"><Link to="/hire">Hire an SMM</Link></Button><Button asChild variant="inverseOutline" size="lg"><Link to="/trainees">Join the masterclass</Link></Button></div></div></section>
  </>;
}
